/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.sql.ResultSet;
import models.Usuario;

import javax.swing.*;
import java.util.Date;
import sql.Sql;

/**
 *
 * @author alyso
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastroUsuario() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeUsuario = new javax.swing.JTextField();
        cpfUsuario = new javax.swing.JTextField();
        dataDeNascimento = new javax.swing.JTextField();
        caixaItem_tipoUsuario = new javax.swing.JComboBox<>();
        tituloSCE1 = new javax.swing.JLabel();
        tituloSCE = new javax.swing.JLabel();
        tituloSCE2 = new javax.swing.JLabel();
        tituloSCE3 = new javax.swing.JLabel();
        tituloSCE4 = new javax.swing.JLabel();
        tituloSCE5 = new javax.swing.JLabel();
        tituloSCE6 = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        logo_menor = new javax.swing.JLabel();
        senhaUsuario = new javax.swing.JPasswordField();
        botaoCadastrarUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BotaoSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeUsuario1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        caixaItem_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "________________", "Administrativo", "Professor", "Aluno" }));
        caixaItem_tipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaItem_tipoUsuarioActionPerformed(evt);
            }
        });

        tituloSCE1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tituloSCE1.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE1.setText("SISTEMA DE CONTROLE ACADÊMICO");

        tituloSCE.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tituloSCE.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE.setText("NOME COMPLETO:");

        tituloSCE2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        tituloSCE2.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE2.setText("CADASTRO DE USUÁRIO");

        tituloSCE3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tituloSCE3.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE3.setText("CPF:");

        tituloSCE4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tituloSCE4.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE4.setText("TIPO DE USUÁRIO:");

        tituloSCE5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tituloSCE5.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE5.setText("DATA DE NASCIMENTO:");

        tituloSCE6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        tituloSCE6.setForeground(new java.awt.Color(0, 102, 0));
        tituloSCE6.setText("SENHA:");

        botaoVoltar.setForeground(new java.awt.Color(0, 102, 0));
        botaoVoltar.setText("Voltar");
        botaoVoltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        logo_menor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/imagens/logo100x100.png"))); // NOI18N

        botaoCadastrarUsuario.setForeground(new java.awt.Color(0, 102, 0));
        botaoCadastrarUsuario.setText("Cadastrar");
        botaoCadastrarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        botaoCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logo_menor)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tituloSCE1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(tituloSCE2)))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloSCE3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloSCE4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloSCE5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloSCE, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloSCE6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(caixaItem_tipoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, 0, 343, Short.MAX_VALUE)
                            .addComponent(dataDeNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cpfUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(senhaUsuario))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(tituloSCE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloSCE2))
                    .addComponent(logo_menor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSCE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSCE3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSCE5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaItem_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloSCE4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloSCE6)
                    .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        BotaoSair.setBackground(new java.awt.Color(204, 204, 204));
        BotaoSair.setText("SAIR");
        BotaoSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/imagens/administrador_icon.png"))); // NOI18N

        nomeUsuario1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        nomeUsuario1.setForeground(new java.awt.Color(0, 102, 0));
        nomeUsuario1.setText("nome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nomeUsuario1))
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaItem_tipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaItem_tipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaItem_tipoUsuarioActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        new TelaAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed
    private void cadastroConcluido(){
        new TelaLogin().setVisible(true);
        this.dispose();
        
    }
    private void botaoCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        if(nomeUsuario.getText().equals("") || cpfUsuario.getText().equals("") || dataDeNascimento.getText().trim().equals("") ||senhaUsuario.getText().trim().equals("") || caixaItem_tipoUsuario.getSelectedItem().equals("________________")){
            JOptionPane.showMessageDialog(null, "Dados incompletos!");
        }else{
            try{

                Usuario usuario = new Usuario();

                try{
                    Date data = new Date(dataDeNascimento.getText());
                    usuario.setDataDeNascimento(data);
                }catch (Exception e){
                    throw new Exception("Formato de Data errada\nDigite a data no formato dd/mm/aaaa");
                }
                String cpf = cpfUsuario.getText().trim().replaceAll("[.,-]", "");
                if(cpf.length() < 11 || cpf.length() > 11){
                    throw new Exception("CPF inválido!\nDigite todos os dígitos!");
                }
                usuario.setCpf(cpf);
                usuario.setNome(nomeUsuario.getText());
                usuario.setSenha(senhaUsuario.getText());
                usuario.setTipo((String) caixaItem_tipoUsuario.getSelectedItem());
                usuario.save();
                String []data = dataDeNascimento.getText().split("/");
                String novaData = data[2]+"-"+data[1]+"-"+data[0];
                new Sql("INSERT INTO dadosCadastrais VALUES('"+usuario.getCpf()+"','"+usuario.getNome()+"','"+usuario.getTipo()+"','"+novaData+"','"+usuario.getSenha()+"');"){
                    @Override
                    public void onQueryConcluida(ResultSet rs) {
                        JOptionPane.showMessageDialog(null,"Cadastro Concluido!");
                        cadastroConcluido();
                        
                    }

                    @Override
                    public void onQueryErro(String feedback) {
                        JOptionPane.showMessageDialog(null,"Erro ao efetivar o cadastro, verifique sua conexão com a internet!");
                    }
                }.start();
            }catch (Exception e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }


    }//GEN-LAST:event_botaoCadastrarUsuarioActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoSair3;
    private javax.swing.JButton botaoCadastrarUsuario;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JComboBox<String> caixaItem_tipoUsuario;
    private javax.swing.JTextField cpfUsuario;
    private javax.swing.JTextField dataDeNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logo_menor;
    private javax.swing.JTextField nomeUsuario;
    private javax.swing.JLabel nomeUsuario1;
    private javax.swing.JPasswordField senhaUsuario;
    private javax.swing.JLabel tituloSCE;
    private javax.swing.JLabel tituloSCE1;
    private javax.swing.JLabel tituloSCE2;
    private javax.swing.JLabel tituloSCE3;
    private javax.swing.JLabel tituloSCE4;
    private javax.swing.JLabel tituloSCE5;
    private javax.swing.JLabel tituloSCE6;
    // End of variables declaration//GEN-END:variables
}
